"""coluna de numero_quarto não é mais único

Revision ID: 000845f74e55
Revises: 525d44b89ce4
Create Date: 2026-03-23 15:23:55.415603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000845f74e55'
down_revision = '525d44b89ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarto', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_quarto_numero_quarto'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarto', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_quarto_numero_quarto'), ['numero_quarto'])

    # ### end Alembic commands ###
