"""Alterando o campo user para username

Revision ID: 471c095b7f04
Revises: 9610d4932676
Create Date: 2026-03-12 15:13:51.016909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471c095b7f04'
down_revision = '9610d4932676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
