"""fix: naming convention and password length

Revision ID: 525d44b89ce4
Revises: 
Create Date: 2026-03-20 16:59:38.856915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525d44b89ce4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=25), nullable=False),
    sa.Column('numero_quarto', sa.Integer(), nullable=False),
    sa.Column('hospede', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarto')),
    sa.UniqueConstraint('numero_quarto', name=op.f('uq_quarto_numero_quarto'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('username', name=op.f('uq_usuario_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('quarto')
    # ### end Alembic commands ###
