"""empty message

Revision ID: 54b359019859
Revises: 471c095b7f04
Create Date: 2026-03-12 23:12:19.481077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b359019859'
down_revision = '471c095b7f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarto', schema=None) as batch_op:
        batch_op.drop_column('cidade')

    # ### end Alembic commands ###
