"""atualizando os dados de usuário

Revision ID: 736ea6eba345
Revises: ef52dbeab0ce
Create Date: 2026-03-12 14:46:18.890406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736ea6eba345'
down_revision = 'ef52dbeab0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=50), nullable=False))
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('email')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=60), nullable=False))
        batch_op.alter_column('senha',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.drop_column('user')

    # ### end Alembic commands ###
