"""Criando a tabela de quartos

Revision ID: 9610d4932676
Revises: 736ea6eba345
Create Date: 2026-03-12 14:54:21.087397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9610d4932676'
down_revision = '736ea6eba345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_quarto', sa.Integer(), nullable=False),
    sa.Column('hospede', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_quarto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quarto')
    # ### end Alembic commands ###
